### PR TITLE
Update to React 15.4.0 and drop dom-server functions from core

### PR DESCRIPTION
**Pull request by Deraen**
More info in #275

### CODE REVIEW

**Comment by yogthos** [comment]
@holmsand @mike-thompson-day8  this looks good to me,  if there aren't any objections I'd like to merge this in

**Comment by si14** [comment]
Do you guys think this PR warrants a release? :)

**Comment by Deraen** [comment]
Yes, definitely. Latest release is also missing https://github.com/reagent-project/reagent/commit/a5ff3b23a7ae517da73d731db4eef0eb77da325f https://github.com/reagent-project/reagent/commit/b65afde4d7ac4864d7e355acdc16977cb92afa3c, which is why I have been using a fork in several projects since 0.6.0 release.

**Comment by yogthos** [comment]
I think we should probably cut a `0.6.1` release then. Myself or @mike-thompson-day8 should be able to push one out to Clojars.

**Comment by yogthos** [comment]
ok `0.6.1` is up on Clojars, if nobody finds any problems we can close this I think

**Comment by Deraen** [comment]
Thanks! @yogthos @mike-thompson-day8 Btw, I'd be happy to help with maintaining Reagent. As I maintain Cljsjs/react it would be easy for me to keep the React dependency here up-to-date, and as we use Reagent at Metosin for all of our frontend code, I do also have interest in developing Reagent further.

**Comment by yogthos** [comment]
@Deraen That sounds fantastic! What's your clojars handle, I'll add you on Clojars as well.

**Comment by Deraen** [comment]
@yogthos I'm deraen there as well: https://clojars.org/deraen

**Comment by yogthos** [comment]
Excellent, you're in. :)

**Comment by Deraen** [comment]
@yogthos Great, btw. I'm still missing the github privileges.

**Comment by yogthos** [comment]
fixed

**Pull request merged**
