### PR TITLE
Support for registering custom components

### LINKED ISSUE #48: Custom tags
When doing server side rendering, to use components you have to manually traverse the generated html and enhance the special nodes, as you cannot return a reference to a fn from the server.

Example:
(defn my-component [n]
  [:span (str n)])

Returned from the server:
[:div [:my-component 3]]

From there I manually scan it and replace :my-component for the fn reference.

Something like this would solve the problem and avoid to scan:
(r/register-component! my-component :my-component)

### PR DESCRIPTION
**Pull request by galdolber**
Fixes #48

### CODE REVIEW

**Comment by galdolber** [comment]
This was taken from https://github.com/k2052/reagent/commit/9a6ab3ba9a833868148aeb9a98e1d1a77ed43da5

**Comment by awb99** [comment]
Will this be merged eventually?

**Comment by Deraen** [comment]
The feature will probably be added, but the implementation will be different than one in this PR.

**Comment by mike-thompson-day8** [comment]
@Deraen  I'm getting close to needing this feature in re-frame in a future release.  I was wondering what your plans where in this area, and if there was anything I could do to help this along?

**Comment by Deraen** [comment]
@mike-thompson-day8 My plan is to use Compiler interface to allow replacing the method used to create elements, so user can handle custom tags there. Could work even now by creating custom compiler with `make-element` which handles certain keywords, something like:

```
(defn make-element-custom [this argv component jsprops first-child]
  (let [component (case component :custom foobar-component component)]
    (tmpl/make-element this argv component jsprops first-child)))
```

Though `make-element` has to return React element directly, so that could be too low level for this. As-element / vec-to-elem could be better level to handle Reagent elements.

https://github.com/reagent-project/reagent/blob/master/src/reagent/impl/template.cljs#L296

But the Compiler interface and tmpl functions aren't (yet) part of the public API, so they could still change.

This isn't very simple, but I think this will be advanced feature and it doesn't need to be simple to use.

I'd also like to hear what is the usecase in Re-frame from custom elements.

**Comment by Deraen** [comment]
Lets continue on a new issue: https://github.com/reagent-project/reagent/issues/503

**Pull request closed without merging**
