### PR TITLE
Remove global karma dependencies

### PR DESCRIPTION
**Pull request by alex-dixon**
#339

### CODE REVIEW

**Comment by danielcompton** [comment]
`karma-cli` is a wrapper around the local Karma that is installed, you can have it globally installed and still use many different versions of the `karma` library in different projects. Would it be sufficient to add documentation to explain what is required here?

**Comment by alex-dixon** [comment]
Of course! I thought this might be nicer but that's just me. 

I didn't realize `karma-cli` was a wrapper. Surprisingly that doesn't seem to affect my thinking much.
It's still one less step/thing to read for contributors. `karma-cli` as dependency. Even though it's not an explicit one it's still there I think -- you could end up with different versions of it on devs machines and across CI runs, which could produce inconsistent test results for no apparent reason.

**Comment by danielcompton** [comment]
> Even though it's not an explicit dependency it's still there I think -- you could end up with different versions of it on devs machines and across CI runs, which could produce inconsistent test results for no apparent reason.

karma-cli is meant to be a very stable wrapper that doesn't change much, it's only 80 lines of JS, with the last [release](https://github.com/karma-runner/karma-cli/releases) in 2016. There should be basically no scenario where you get inconsistent test results as it is just a launcher. See https://github.com/bensu/doo/pull/46 for more details on why using `karma-cli` is preferable, particularly around Windows support.

I think it would definitely be good for the development docs to mention installing `karma-cli`, I didn't see it mentioned on a quick scan through.

**Comment by alex-dixon** [comment]
I can see you’re a seasoned expert on these matters. 

A test runner that’s downloaded 4 million times a week and requires the installation of a second package for command line support was unexpected for me. I’m sure there’s a lesson and a story or two in there somewhere. 

Nondeterminism in resolving npm packages bothers me very much. If I read the code correctly it says “resolve karma relative to the pwd (wherever that is) and if there’s a karma there then great! Let’s use that, whatever version it happens to be. ” If it doesn’t find a karma in this non deterministic way, it doubles down and looks for a globally installed version. If that’s found, great! Use it, whatever version it happens to be. 

The only thing I can think would aid windows support is a call to [path.normalize](https://nodejs.org/api/path.html#path_path_normalize_path) [here](https://github.com/karma-runner/karma-cli/blob/3be8633c616faae78fbb4cc841b9b19636c5a075/bin/karma#L76) which enforces platform specific slashes and the regex [here](https://github.com/karma-runner/karma-cli/blob/3be8633c616faae78fbb4cc841b9b19636c5a075/bin/karma#L54) which appears to do the same thing. 

Maybe ‘doo’ wasn’t/isn’t performing that step?

**Comment by Deraen** [comment]
We already use locked down version of Karma (and plugins), see [package.json](https://github.com/reagent-project/reagent/blob/master/package.json). We should just document that `karma-cli` should be globally installed befory trying to run the tests.

**Comment by Deraen** [comment]
Added mention about this to dev docs: https://github.com/reagent-project/reagent/commit/ae532864ce64ec4a7d4030611b44507ff43cd893

**Comment by Deraen** [comment]
@alex-dixon Do you agree the documentation is enough? This and the issue can be close?

**Comment by alex-dixon** [comment]
Sounds good. Thank you for the informative discussion @danielcompton @Deraen!

**Pull request closed without merging**
