### PR TITLE
Make use of deftype constructor instead of interop

### PR DESCRIPTION
**Pull request by EduardoMRB**
As Stuart Sierra stated in his [blog post](http://stuartsierra.com/2015/05/17/clojure-record-constructors)
we should use `deftype` and `defrecord` constructor functions or create
our own constructor functions for types and records.

### CODE REVIEW

**Comment by JulianLeviston** [comment]
It'd be nice if there were reasons given for doing things. "Because Stuart Says So" isn't a true reason.

In this case, it's pretty obvious that he's advocating not relying on the current implementation of Clojure because it may change in the future, but cargo culting is just something to watch out for.

**Comment by EduardoMRB** [comment]
Hi @JulianLeviston ,

I think I gave the wrong impression, sorry about that.

I believe that using constructor functions make the code more clear. If I see `->Foo`, I know that `Foo` is either a record or a type and not a java or js class.

**Comment by JulianLeviston** [comment]
Fair point! :)

**Comment by mike-thompson-day8** [comment]
I think this should be merged (although currently has conflicts).

**Comment by EduardoMRB** [comment]
@mike-thompson-day8 I think it's ok now.

**Comment by Deraen** [comment]
Merged in https://github.com/reagent-project/reagent/pull/288

**Pull request closed without merging**
