### PR TITLE
Fix doc formatting

### PR DESCRIPTION
**Pull request by sir-pinecone**
Just fixing up some indentation.

### CODE REVIEW

**Comment by Deraen** [comment]
While some docstrings are clearly indented badly, in some cases you are just changing the indentation style.

It is matter of opinion how to indent the docstrings. Afaik most editors (Emacs, Vim) align multi-line strings (including docstrings) to the column where " is on the first line: https://github.com/bbatsov/clojure-style-guide#align-docstring-lines. Also, clojure.core uses this style.

**Comment by sir-pinecone** [comment]
@Deraen Ah yes, that's a good point. I'll fix this up and revert the indentation changes that go against the clojure.core style.

**Comment by sir-pinecone** [comment]
OK, fixed up my change.

**Comment by holmsand** [comment]
Thanks!

**Pull request merged**
