### PR TITLE
New test runner

### PR DESCRIPTION
**Pull request by Deraen**
Current pre-rendering runner and test runner is quite complex.

I think it will be good to replace custom test runner with Doo. With Doo we can easily run tests on Chrome and other envs in addition to Node.

### CODE REVIEW

**Comment by Deraen** [comment]
That would probably allow starting js env (Chrome) and karma once and then running several tests on same env? That should make tests faster. I'll consider it.

**Comment by Deraen** [comment]
Test runner now works very well. Tests are now run against several environments.

These change also take care of adding support for React 16. The default is still 15, but the tests are now run against React 16 also. To get tests working, I needed to fix `component-path` and use `after-render` in some `testwrap` tests. I also added test to check new error boundary feature works.

I'm still fixing scripts to build and deploy the site.

**Comment by Deraen** [comment]
Okay, got the demo site building & deploying correctly now: https://github.com/reagent-project/reagent-project.github.io/commit/4be71ec363585613574cfcc0dce15f57f53d813e

So this is quite a lot of changes, but I hope they make sense. I think the result is that the tests now run in more realistic environments, and they are run against multiple environments. As result of running tests takes more time, around 10 mins currently, but this can be probably made a bit faster later (using CircleCI v2, running tests parallel, reducing test environments).

- No custom JS test runner / pre-render main -> Doo and Prerender Node main is written in Cljs now
- Test script reports status of each test at the end:
```
OK   browser-node
OK   browser-node-react-16
OK   browser-umd
OK   browser-umd-prod
OK   browser-umd-react-16
OK   node
```
- Karma writes out Junit reports, Circle uses this to display test summary: "Your build ran 515 tests in unknown with 0 failures"
- Makefile -> Bash scripts, I prefer working with Bash myself
- I removed Webpack config for now, I'm quite sure it was out-of-date, we can add it back later, with tests, if there is interest in that
- No Lein profile merging with Cljsbuild, this had some problems with Doo, I think, so I decided to just write out all different configurations using Cljsbuild configuration.
- **React 16**:
    - Default is still React 15
    - Tests are run against and pass with React 16
    - `testwrap` required using `after-render` for running some tests, not sure why `ratom` tests in `testreagent` don't need this :(
    - I added support for error boundaries, i.e. `:component-did-catch` lifecycle method, and there is a test for this which is ran when React.version is >= 16: https://github.com/reagent-project/reagent/pull/313/files#diff-17453196983b87ab1421488f4680e353R993
- Some test util changes, `with-mounted-component` renders the React to a DOM component, but doesn't mount to component to `body`, as that doesn't seem to be necessary and saves a bit of work at clean up

**Comment by gadfly361** [comment]
@Deraen Reagent community at large is thankful for all the work you have been putting in to keep this project going!

I tried running the tests and this is my output:

```
~/gadfly/projects/reagent(new-test-runner)$ ./run-tests.sh 
##
## TESTING browser-node
##

+ lein do clean, doo chrome-headless test once
[eval]:1
let fs = require('fs');
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at Object.exports.runInThisContext (vm.js:53:16)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:410:26)
    at node.js:578:27
    at nextTickCallbackWith0Args (node.js:419:9)
    at process._tickCallback (node.js:348:13)


;; ======================================================================
;; Testing with Chrome-headless:

HeadlessChrome 0.0.0 (Linux 0.0.0) ERROR
  Uncaught TypeError: Cannot read property 'call' of undefined
  at target/cljsbuild/test/out/reagenttest/testreagent.js:2398
HeadlessChrome 0.0.0 (Linux 0.0.0): Executed 0 of 0 ERROR (0.592 secs / 0 secs)
Subprocess failed

FAIL browser-node


##
## TESTING browser-node-react-16
##

+ lein do clean, doo chrome-headless test once
[eval]:1
let fs = require('fs');
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at Object.exports.runInThisContext (vm.js:53:16)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:410:26)
    at node.js:578:27
    at nextTickCallbackWith0Args (node.js:419:9)
    at process._tickCallback (node.js:348:13)


;; ======================================================================
;; Testing with Chrome-headless:

HeadlessChrome 0.0.0 (Linux 0.0.0) ERROR
  Uncaught TypeError: Cannot read property 'call' of undefined
  at target/cljsbuild/test/out/reagenttest/testreagent.js:2398
HeadlessChrome 0.0.0 (Linux 0.0.0): Executed 0 of 0 ERROR (0.635 secs / 0 secs)
Subprocess failed

FAIL browser-node-react-16


##
## TESTING browser-umd
##

+ lein do clean, doo chrome-headless test once

;; ======================================================================
;; Testing with Chrome-headless:

LOG: 'Testing reagenttest.testreagent'
........................................
LOG: 'Testing reagenttest.testcursor'
..............
LOG: 'Testing reagenttest.testinterop'
..
LOG: 'Testing reagenttest.testratom'
................
LOG: 'Testing reagenttest.testratomasync'
.........
LOG: 'Testing reagenttest.testtrack'
..........
LOG: 'Testing reagenttest.testwithlet'
......
LOG: 'Testing reagenttest.testwrap'
......
HeadlessChrome 0.0.0 (Linux 0.0.0): Executed 103 of 103 SUCCESS (0.522 secs / 57.895 secs)
+ test -f target/cljsbuild/test/out/cljsjs/react/development/react.inc.js


##
## TESTING browser-umd-prod
##

+ lein do clean, doo chrome-headless prod-test once
WARNING: :preloads should only be specified with :none optimizations

;; ======================================================================
;; Testing with Chrome-headless:

LOG: 'Testing reagenttest.testreagent'
........................................
LOG: 'Testing reagenttest.testcursor'
..............
LOG: 'Testing reagenttest.testinterop'
..
LOG: 'Testing reagenttest.testratom'
................
LOG: 'Testing reagenttest.testratomasync'
.........
LOG: 'Testing reagenttest.testtrack'
..........
LOG: 'Testing reagenttest.testwithlet'
......
LOG: 'Testing reagenttest.testwrap'
......
HeadlessChrome 0.0.0 (Linux 0.0.0): Executed 103 of 103 SUCCESS (0.795 secs / 37.685 secs)
+ test -f target/cljsbuild/prod-test/main.js


##
## TESTING browser-umd-react-16
##

+ lein with-profile dev,react-16 do clean, doo chrome-headless test once
Retrieving cljsjs/react/16.0.0-0/react-16.0.0-0.pom from clojars
Retrieving cljsjs/react-dom/16.0.0-0/react-dom-16.0.0-0.pom from clojars
Retrieving cljsjs/react-dom-server/16.0.0-0/react-dom-server-16.0.0-0.pom from clojars
Retrieving cljsjs/react-dom/16.0.0-0/react-dom-16.0.0-0.jar from clojars
Retrieving cljsjs/react/16.0.0-0/react-16.0.0-0.jar from clojars
Retrieving cljsjs/react-dom-server/16.0.0-0/react-dom-server-16.0.0-0.jar from clojars

;; ======================================================================
;; Testing with Chrome-headless:

LOG: 'Testing reagenttest.testreagent'
........................................
LOG: 'Testing reagenttest.testcursor'
..............
LOG: 'Testing reagenttest.testinterop'
..
LOG: 'Testing reagenttest.testratom'
................
LOG: 'Testing reagenttest.testratomasync'
.........
LOG: 'Testing reagenttest.testtrack'
..........
LOG: 'Testing reagenttest.testwithlet'
......
LOG: 'Testing reagenttest.testwrap'
......
HeadlessChrome 0.0.0 (Linux 0.0.0): Executed 103 of 103 SUCCESS (0.529 secs / 49.402 secs)
+ test -f target/cljsbuild/test/out/cljsjs/react/development/react.inc.js


##
## TESTING node
##

+ lein do clean, doo node node-test once

;; ======================================================================
;; Testing with Node:


Testing reagenttest.testreagent

Testing reagenttest.testcursor

Testing reagenttest.testinterop

Testing reagenttest.testratom

Testing reagenttest.testratomasync

Testing reagenttest.testtrack

Testing reagenttest.testwithlet

Testing reagenttest.testwrap
+ test '!' -f target/cljsbuild/node-test/out/node_modules/react/index.js
+ grep 'reagent.impl.template.node$module$react = require('\''react'\'')' target/cljsbuild/node-test/out/reagent/impl/template.js
reagent.impl.template.node$module$react = require('react');


##
## SUMMARY
##

FAIL browser-node
FAIL browser-node-react-16
OK   browser-umd
OK   browser-umd-prod
OK   browser-umd-react-16
OK   node
```

Steps to reproduce:
I downloaded a clean copy of reagent, checked out your branch, ran prepare-tests.sh, then ran run-tests.sh. I also manually ran npm install in all of the test-environments (I missed the prepare-tests.sh initially)

**Comment by Deraen** [comment]
@gadfly361 Which node version are you running?

ClojureScript node module integration code requires ES6 support, which I think required at least Node 6, I'm running Node 8 myself:

```
❯ node --version
v8.4.0
```

(Reagent itself works with older Node, as seen with node test-env).

**Comment by gadfly361** [comment]
@Deraen Ah good catch, was using an old node version. That's what happens when you use NVM and forget to switch :grin:

**Pull request merged**
